uart:
  id: uart_modbus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 19200
  data_bits: 8
  parity: EVEN
  stop_bits: 1

modbus:
  uart_id: uart_modbus
  id: modbus1

modbus_controller:
- id: modbus_device
  address: 0x1
  modbus_id: modbus1
  setup_priority: -10
  update_interval: ${update_interval}

sensor:
# -- ventilation level ---
- platform: combination
  name: "Ventilation Level"
  id: 'zehnder_ventilation_level'
  icon: mdi:fan
  type: max
  sources:
    - source: zehnder_analog_control_setpoint
    - source: zehnder_rf_control_setpoint
    - source: zehnder_three_way_control_setpoint
    - source: zehnder_bathroom_control_setpoint

# --- fan states ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan duty cycle"
  icon: mdi:fan
  register_type: holding
  address: 0x136
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  id: zehnder_exhaust_duty
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan duty cycle"
  icon: mdi:fan
  register_type: holding
  address: 0x137
  unit_of_measurement: "%"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  id: zehnder_supply_duty
  filters:
    - multiply: 0.1

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan flow rate"
  register_type: holding
  address: 0x138
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  state_class: "measurement"
  id: zehnder_exhaust_flow
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan flow rate"
  register_type: holding
  address: 0x139
  unit_of_measurement: "m³/h"
  value_type: U_WORD
  device_class: "volume_flow_rate"
  state_class: "measurement"
  id: zehnder_supply_flow

- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan speed"
  icon: mdi:fan
  register_type: holding
  address: 0x13A
  unit_of_measurement: "RPM"
  value_type: U_WORD
  state_class: "measurement"
  id: zehnder_exhaust_rpm
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan speed"
  icon: mdi:fan
  register_type: holding
  address: 0x13B
  unit_of_measurement: "RPM"
  value_type: U_WORD
  state_class: "measurement"
  id: zehnder_supply_rpm

# --- temperatures ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Outdoor air temperature"
  register_type: holding
  address: 0x12C
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t1
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Pre-heater temperature"
  register_type: holding
  address: 0x12D
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t2
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply air temperature"
  register_type: holding
  address: 0x12F
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t4
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Extract air temperature"
  register_type: holding
  address: 0x130
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t5
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust air temperature"
  register_type: holding
  address: 0x131
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_type: S_WORD
  id: zehnder_t6
  accuracy_decimals: 1
  state_class: "measurement"
  filters:
    - multiply: 0.1

# --- humidity ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Outdoor humidity"
  id: zehnder_outdoor_humidity
  register_type: holding
  address: 0x132
  state_class: "measurement"
  device_class: 'humidity'
  value_type: U_WORD
  unit_of_measurement: '%'
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply humidity"
  id: zehnder_supply_humidity
  register_type: holding
  address: 0x133
  state_class: "measurement"
  value_type: U_WORD
  device_class: 'humidity'
  unit_of_measurement: '%'
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Extract humidity"
  id: zehnder_extract_humidity
  register_type: holding
  address: 0x134
  state_class: "measurement"
  value_type: U_WORD
  device_class: 'humidity'
  unit_of_measurement: '%'
  filters:
    - multiply: 0.1
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust humidity"
  id: zehnder_exhaust_humidity
  register_type: holding
  address: 0x135
  state_class: "measurement"
  device_class: 'humidity'
  value_type: U_WORD
  unit_of_measurement: '%'
  filters:
    - multiply: 0.1

# --- bypass ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Bypass motor active"
  id: zehnder_bypass_motor_active
  register_type: holding
  address: 0x145
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Bypass setpoint"
  id: zehnder_bypass_setpoint
  register_type: holding
  address: 0x146
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Bypass Position"
  id: zehnder_bypass_position
  register_type: holding
  address: 0x147
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
  
# --- control setpoints ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Analog (0-10V) control setpoint"
  id: zehnder_analog_control_setpoint
  icon: mdi:fan
  register_type: holding
  address: 0x148
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "RF control setpoint"
  id: zehnder_rf_control_setpoint
  icon: mdi:fan
  register_type: holding
  address: 0x149
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "3-way switch control setpoint"
  id: zehnder_three_way_control_setpoint
  icon: mdi:fan
  register_type: holding
  address: 0x14A
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Bathroom switch control setpoint"
  id: zehnder_bathroom_control_setpoint
  icon: mdi:fan
  register_type: holding
  address: 0x14B
  unit_of_measurement: "%"
  value_type: U_WORD
  state_class: "measurement"
  disabled_by_default: true

# --- input voltage ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Analog (0-10V) input voltage"
  id: zehnder_analog_input_voltage
  register_type: holding
  address: 0x13C
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  disabled_by_default: true
  device_class: 'voltage'
  filters:
    - multiply: 0.01
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "RF input voltage"
  id: zehnder_rf_input_voltage
  register_type: holding
  address: 0x13D
  unit_of_measurement: "V"
  value_type: U_WORD
  accuracy_decimals: 1
  state_class: "measurement"
  disabled_by_default: true
  device_class: 'voltage'
  filters:
    - multiply: 0.01

# --- flow rate setpoint ---
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Exhaust fan flow rate setpoint"
  id: zehnder_exhaust_flow_setpoint
  register_type: holding
  address: 0x141
  state_class: "measurement"
  disabled_by_default: true
  value_type: U_WORD
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Supply fan flow rate setpoint"
  id: zehnder_supply_flow_setpoint
  register_type: holding
  address: 0x140
  state_class: "measurement"
  disabled_by_default: true
  value_type: U_WORD
  unit_of_measurement: "m³/h"
  device_class: "volume_flow_rate"

# --- device info ---
- platform: modbus_controller
  internal: true
  modbus_controller_id: modbus_device
  entity_category: "diagnostic"
  name: "Firmware version (raw)"
  id: zehnder_firmware_version_raw
  address: 0x6E
  register_type: holding
  value_type: U_WORD # 20800 = 2.8.0 (Major.Minor.Patch with 2 digits)
  on_value: 
    then:
      - text_sensor.template.publish:
          id: zehnder_firmware_version
          state: !lambda |-
            int value = id(zehnder_firmware_version_raw).state;
            int major = value / 10000;      // Extract the major version
            int minor = (value / 100) % 100; // Extract the minor version
            int patch = value % 100;         // Extract the patch version
            return std::to_string(major) + "." + std::to_string(minor) + "." + std::to_string(patch);

text_sensor:
  - platform: template
    name: "Firmware version"
    id: zehnder_firmware_version
    update_interval: never
    entity_category: "diagnostic"
    
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Status"
    id: zehnder_status
    entity_category: "diagnostic"
    address: 0x65
    register_type: holding
    raw_encode: HEXBYTES
    lambda: |-
        uint16_t value = modbus_controller::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("Fault");
          case 2: return std::string("Self-test");
          case 10: return std::string("Normal");
          case 20: return std::string("Standby");
          case 42: return std::string("Maintenance Mode");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;
  
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Orientation"
    id: zehnder_orientation
    register_type: holding
    entity_category: "diagnostic"
    address: 0x6F
    raw_encode: HEXBYTES
    lambda: |-
        uint16_t value = modbus_controller::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("Right");
          case 1: return std::string("Left");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;
        
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Model"
    id: zehnder_model
    register_type: holding
    entity_category: "diagnostic"
    address: 0x70
    raw_encode: HEXBYTES
    lambda: |-
        uint16_t value = modbus_controller::word_from_hex_str(x, 0);
        switch (value) {
          case 0: return std::string("E300 P");
          case 2: return std::string("E300 RF");
          case 4: return std::string("E400 RF");
          default: return std::string("Unknown (") + std::to_string(value) + ")";
        }
        return x;
  
binary_sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "RF input enabled"
  address: 0x13E
  register_type: holding
  entity_category: "diagnostic"
  id: zehnder_rf_input_enabled
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Pre-heater active"
  address: 0x13F
  register_type: holding
  id: zehnder_pre_heater_active
  device_class: heat
- platform: template
  name: "Bypass"
  id: zehnder_bypass
  device_class: opening
  lambda: |-
    if (id(zehnder_bypass_position).state > 0) {
      return true;
    } else {
      return false;
    }
- platform: modbus_controller
  modbus_controller_id: modbus_device
  internal: true
  address: 0x152
  register_type: holding
  id: zehnder_pre_heater_present_internal
- platform: template
  name: "Pre-heater present"
  entity_category: "diagnostic"
  id: zehnder_pre_heater_present
  lambda: |-
    if (id(zehnder_firmware_version_raw).state > 19999) { // only available on firmware 2.0.0+
      return id(zehnder_pre_heater_present_internal).state;
    } else {
      return {};
    }
- platform: modbus_controller
  modbus_controller_id: modbus_device
  internal: true
  address: 0x151
  register_type: holding
  id: zehnder_fireplace_mode_internal
- platform: template
  name: Fireplace mode
  id: zehnder_fireplace_mode
  lambda: |-
    if (id(zehnder_firmware_version_raw).state > 19999) { // only available on firmware 2.0.0+
      return id(zehnder_fireplace_mode_internal).state;
    } else {
      return {};
    }